spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: D3sarr0ll0
    url: jdbc:mariadb://localhost:3306/MOGESDOC
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
